server:
  port: 8000
  servlet:
    context-path: /

spring:
  application:
    name: syncfield-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

syncfield:
  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    expiration-ms: 86400000 # 24 hours
  storage:
    local-dir: ${STORAGE_LOCAL_DIR:./storage-uploads}
    supabase-url: ${SUPABASE_URL:https://bdahyquskpiiapwttsvw.supabase.co}
    supabase-key: ${SUPABASE_SERVICE_KEY:}
    bucket-name: ${SUPABASE_STORAGE_BUCKET:evidence-vault}

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:syncfield;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    driverClassName: ${DATABASE_DRIVER:org.h2.Driver}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:}
  jpa:
    database-platform: ${DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require}
    driverClassName: org.postgresql.Driver
    username: ${DATABASE_USERNAME:postgres.bdahyquskpiiapwttsvw}
    password: ${DATABASE_PASSWORD:Kamesh2006.0}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
